version: "3"
    
services:
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    networks:
      - seu-investimento

networks:
  seu-investimento:
    driver: bridge
